file.CreateDir("CPUChip")
file.CreateDir("GPUChip")
file.CreateDir("SPUChip")
file.CreateDir("adv_duplicator")
file.CreateDir("Expression2")

file.CreateDir("CPUChip/lib")
file.CreateDir("CPUChip/lib/drivers")
file.CreateDir("CPUChip/lib/zcrt")
file.CreateDir("CPUChip/examples")
file.CreateDir("CPUChip/programs")
file.CreateDir("GPUChip/examples")
file.CreateDir("GPUChip/lib")
file.CreateDir("GPUChip/lib/drivers")